version: '3.9'

services:
  user-service:
    build: 
      context: ./services/user
    container_name: user-container
    env_file: "./.env"
    volumes:
      - user_data:/app/data
    networks:
      - trancendence-network
    restart: unless-stopped

  stats-service:
    build: 
      context: ./services/stats
    container_name: stats-container
    env_file: "./.env"
    volumes:
      - tournament_data:/app/data
    networks:
      - trancendence-network
    restart: unless-stopped
  
  gateway-service:
    build:
      context: ./gateway
    container_name: gateway_container
    env_file: "./.env"
    ports:
      - "8443:8443"
    networks:
      - trancendence-network
    restart: unless-stopped


volumes:
  user_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/services/user/data
  tournament_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/services/stats/data
  
networks:
  trancendence-network:
    name: trancendence-network
    driver: bridge

