services:
  stats-service:
    build: 
      context: ./services/stats-service
    container_name: stats-container
    env_file: "./.env"
    volumes:
      - stats_data:/app/data
    networks:
      - trancendence-network
    restart: unless-stopped

  # Tournament Service
  tournament-service:
    build: 
      context: ./services/tournament-service
    container_name: tournament-container
    env_file: "./.env"
    volumes:
      - tournament_data:/app/data
    networks:
      - trancendence-network
    restart: unless-stopped
  
  gateway-service:
    build:
      context: ./gateway
    container_name: gateway_container
    env_file: "./.env"
    ports:
      - "8443:8443"
    networks:
      - trancendence-network
    restart: unless-stopped

  auth-service:
    build:
      context: ./services/auth-service
      target: dev  # Use development stage for testing
    container_name: auth_container
    env_file: "./services/auth-service/.env"
    networks:
      - trancendence-network
    restart: unless-stopped
    volumes:
      - auth_data:/app/data

  frontend-service:
    build:
      context: ./frontend
    container_name: frontend_container
    networks:
      - trancendence-network
    restart: unless-stopped

volumes:
  stats_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/services/stats-service/data
  tournament_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/services/tournament-service/data
  auth_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/services/auth-service/data
  
networks:
  trancendence-network:
    name: trancendence-network
    driver: bridge

