version: '3.9'

services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service
      - game-service
      - chat-service
      - stats-service
      - i18n-service

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  auth-service:
    build: ./services/auth-service
    environment:
      - DATABASE_URL=file:/data/auth.db
    volumes:
      - auth-data:/data

  user-service:
    build: ./services/user-service
    environment:
      - DATABASE_URL=file:/data/user.db
    volumes:
      - user-data:/data

  game-service:
    build: ./services/game-service
    environment:
      - DATABASE_URL=file:/data/game.db
    volumes:
      - game-data:/data

  chat-service:
    build: ./services/chat-service
    environment:
      - DATABASE_URL=file:/data/chat.db
    volumes:
      - chat-data:/data

  stats-service:
    build: ./services/stats-service
    environment:
      - DATABASE_URL=file:/data/stats.db
    volumes:
      - stats-data:/data

  i18n-service:
    build: ./services/i18n-service

volumes:
  auth-data:
  user-data:
  game-data:
  chat-data:
  stats-data:
