services:
  user-service:
    build: 
      context: ./services/stats-service
    container_name: user-container
    env_file: "./.env"
    volumes:
      - user_data:/app/data
    networks:
      - trancendence-network
    restart: unless-stopped

  # Tournament Service
  tournament-service:
    build: 
      context: ./services/tournament-service
    container_name: tournament-container
    env_file: "./.env"
    volumes:
      - tournament_data:/app/data
    networks:
      - trancendence-network
    restart: unless-stopped
  
  gateway-service:
    build:
      context: ./gateway
    container_name: gateway_container
    env_file: "./.env"
    ports:
      - "8443:8443"
    networks:
      - trancendence-network
    restart: unless-stopped


volumes:
  user_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/services/stats-service/data
  tournament_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/services/tournament-service/data
  
networks:
  trancendence-network:
    name: trancendence-network
    driver: bridge

