name: Backend Integration Tests

on:
  push:
    branches: [ main, integration ]
  pull_request:
    branches: [ main, integration ]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Build and start backend with Makefile
        run: make backend

      - name: Wait for backend to be ready
        run: |
          sleep 15
          curl --insecure --retry 10 --retry-delay 3 https://localhost:8443/as/health || exit 1

      - name: Run pytest integration tests
        run: |
          pytest test_match_history_scores.py
          pytest test_tournament_history.py
