#Github marketplace https://github.com/marketplace
name: Compile the Project

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # uses: Tells GitHub to run an external or reusable action
    - uses: actions/checkout@v4 # Clone your repo into the runner

    - name: Set up Node.js  # Human-readable label for the step (shown in GitHub UI)
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install & test services
      run: |
        cd services/auth-service && npm install && npm test
        cd ../../services/user-service && npm install && npm test

    - name: Check frontend build
      run: |
        cd frontend && npm install && npm run build
