name: Front Compile

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-24.04.2

  steps:
    name: Checkout code
    uses: actions/checkout@v4

    name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: 21

    # It runs npm install inside the front/app/ directory, which reads package.json
    # and downloads the necessary dependencies into node_modules.
    name: Install dependencies
    working-directory: front/app/
    run: npm install
